# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.6.0-dev.20260918.061604Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountApiKey(BaseModel):
    """
    AccountApiKey
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    account: StrictStr
    enabled: StrictBool
    masked_value: Optional[StrictStr] = Field(default=None, alias="maskedValue")
    created_by: StrictStr
    updated_by: StrictStr
    created_at: datetime
    updated_at: datetime
    expires_at: Optional[datetime] = None
    scope: StrictStr
    profile: StrictStr
    last_used_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "account", "enabled", "maskedValue", "created_by", "updated_by", "created_at", "updated_at", "expires_at", "scope", "profile", "last_used_at"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        return value

    @field_validator('profile')
    def profile_validate_enum(cls, value):
        """Validates the enum"""
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountApiKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountApiKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "account": obj.get("account"),
            "enabled": obj.get("enabled"),
            "maskedValue": obj.get("maskedValue"),
            "created_by": obj.get("created_by"),
            "updated_by": obj.get("updated_by"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "expires_at": obj.get("expires_at"),
            "scope": obj.get("scope"),
            "profile": obj.get("profile"),
            "last_used_at": obj.get("last_used_at")
        })
        return _obj


