# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.conversation_visibility import ConversationVisibility
from vertesia_client.openapi.models.interaction_execution_configuration import InteractionExecutionConfiguration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentEventDeliveryTarget(BaseModel):
    """
    AgentEventDeliveryTarget
    """ # noqa: E501
    type: StrictStr
    interaction_ref: Optional[StrictStr] = Field(default=None, description="Interaction ID, app ref, or system ref. Defaults to the general-purpose system agent.")
    data: Optional[Dict[str, Any]] = None
    config: Optional[InteractionExecutionConfiguration] = None
    interactive: Optional[StrictBool] = None
    visibility: Optional[ConversationVisibility] = None
    tags: Optional[List[StrictStr]] = None
    categories: Optional[List[StrictStr]] = None
    tool_names: Optional[List[StrictStr]] = None
    max_iterations: Optional[Union[StrictFloat, StrictInt]] = None
    debug_mode: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["type", "interaction_ref", "data", "config", "interactive", "visibility", "tags", "categories", "tool_names", "max_iterations", "debug_mode"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentEventDeliveryTarget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentEventDeliveryTarget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "interaction_ref": obj.get("interaction_ref"),
            "data": obj.get("data"),
            "config": InteractionExecutionConfiguration.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "interactive": obj.get("interactive"),
            "visibility": obj.get("visibility"),
            "tags": obj.get("tags"),
            "categories": obj.get("categories"),
            "tool_names": obj.get("tool_names"),
            "max_iterations": obj.get("max_iterations"),
            "debug_mode": obj.get("debug_mode")
        })
        return _obj


