# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vertesia_client.openapi.models.mcp_tool_annotations import MCPToolAnnotations
from vertesia_client.openapi.models.tool_source import ToolSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AggregatedTool(BaseModel):
    """
    A single tool entry in the unified registry, regardless of where it came from. Returned by `GET /tools` and the resolution map of `POST /tools/validate`.
    """ # noqa: E501
    name: StrictStr = Field(description="Name as referenced from `agent_runner_options.tool_names`. For interaction skills this is `learn_<endpoint>`.")
    source: ToolSource
    description: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    is_default: Optional[StrictBool] = Field(default=None, description="Whether the tool is part of the default toolkit when no explicit `tool_names` is provided.")
    annotations: Optional[MCPToolAnnotations] = None
    unlocked_tools: Optional[List[StrictStr]] = Field(default=None, description="For skills (`learn_*`): tool names this skill unlocks when invoked.")
    app_install_id: Optional[StrictStr] = Field(default=None, description="Present when `source === 'app'`: the app installation that provides this tool.")
    app_name: Optional[StrictStr] = Field(default=None, description="Present when `source === 'app'`: the app's manifest name (used for `principal.apps` filtering).")
    interaction_id: Optional[StrictStr] = Field(default=None, description="Present when `source === 'interaction'`: the interaction document id.")
    is_agent: Optional[StrictBool] = Field(default=None, description="Present when `source === 'interaction'`: true if the interaction has `agent_runner_options.is_agent === true`. Lets UI consumers distinguish sub-agents (autonomous, run-to-completion) from regular interaction tools.")
    __properties: ClassVar[List[str]] = ["name", "source", "description", "title", "is_default", "annotations", "unlocked_tools", "app_install_id", "app_name", "interaction_id", "is_agent"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AggregatedTool from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of annotations
        if self.annotations:
            _dict['annotations'] = self.annotations.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AggregatedTool from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "source": obj.get("source"),
            "description": obj.get("description"),
            "title": obj.get("title"),
            "is_default": obj.get("is_default"),
            "annotations": MCPToolAnnotations.from_dict(obj["annotations"]) if obj.get("annotations") is not None else None,
            "unlocked_tools": obj.get("unlocked_tools"),
            "app_install_id": obj.get("app_install_id"),
            "app_name": obj.get("app_name"),
            "interaction_id": obj.get("interaction_id"),
            "is_agent": obj.get("is_agent")
        })
        return _obj


