# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, Optional
from vertesia_client.openapi.models.app_access_control import AppAccessControl
from vertesia_client.openapi.models.o_auth_client_credentials import OAuthClientCredentials
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AppInstallationPayload(BaseModel):
    """
    AppInstallationPayload
    """ # noqa: E501
    app_id: StrictStr
    settings: Optional[Dict[str, Any]] = None
    access_control: Optional[AppAccessControl] = Field(default=None, description="Per-installation override of the manifest's `access_control` policy. When provided, takes precedence over the manifest default for every access check. Sibling of `settings` — admin-controlled, not part of the app's own settings JSON.  Three send-time semantics on update:  - Field omitted entirely from the payload → leave the existing override unchanged.  - Explicit `null` → clear the override, fall back to the manifest default.  - String enum → set the override to that value.  (On install, the same shape applies; omit or pass `null` to use the manifest default.)")
    oauth_params: Optional[Dict[str, OAuthClientCredentials]] = Field(default=None, description="OAuth credentials for each collection, keyed by collection.id. Legacy callers may still use collection.name for older manifests. Collected from the user at install time for collections with oauth_config.required_at_install.")
    oauth_provider_params: Optional[Dict[str, OAuthClientCredentials]] = Field(default=None, description="OAuth credentials for named providers, keyed by the provider key from oauth_providers. Collected from the user at install time for providers with required_at_install. Separate from oauth_params to avoid key collisions between provider keys and collection ids.")
    __properties: ClassVar[List[str]] = ["app_id", "settings", "access_control", "oauth_params", "oauth_provider_params"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppInstallationPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in oauth_params (dict)
        _field_dict = {}
        if self.oauth_params:
            for _key_oauth_params in self.oauth_params:
                if self.oauth_params[_key_oauth_params]:
                    _field_dict[_key_oauth_params] = self.oauth_params[_key_oauth_params].to_dict()
            _dict['oauth_params'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in oauth_provider_params (dict)
        _field_dict = {}
        if self.oauth_provider_params:
            for _key_oauth_provider_params in self.oauth_provider_params:
                if self.oauth_provider_params[_key_oauth_provider_params]:
                    _field_dict[_key_oauth_provider_params] = self.oauth_provider_params[_key_oauth_provider_params].to_dict()
            _dict['oauth_provider_params'] = _field_dict
        # set to None if access_control (nullable) is None
        # and model_fields_set contains the field
        if self.access_control is None and "access_control" in self.model_fields_set:
            _dict['access_control'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppInstallationPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "app_id": obj.get("app_id"),
            "settings": obj.get("settings"),
            "access_control": obj.get("access_control"),
            "oauth_params": dict(
                (_k, OAuthClientCredentials.from_dict(_v))
                for _k, _v in obj["oauth_params"].items()
            )
            if obj.get("oauth_params") is not None
            else None,
            "oauth_provider_params": dict(
                (_k, OAuthClientCredentials.from_dict(_v))
                for _k, _v in obj["oauth_provider_params"].items()
            )
            if obj.get("oauth_provider_params") is not None
            else None
        })
        return _obj


