# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AppInstallationProviderBinding(BaseModel):
    """
    Binding between a named OAuth provider and the OAuth provider created for it at install time. Stored on AppInstallation so the runtime can resolve the correct OAuth provider for collections that reference a shared provider via MCPToolCollectionObject.oauth_provider.
    """ # noqa: E501
    provider_key: StrictStr = Field(description="Key from AppManifestData.oauth_providers")
    oauth_provider_id: StrictStr = Field(description="MongoDB ObjectId of the created OAuth provider")
    oauth_provider_name: StrictStr = Field(description="Name of the OAuth provider at creation time (for audit/display only)")
    __properties: ClassVar[List[str]] = ["provider_key", "oauth_provider_id", "oauth_provider_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppInstallationProviderBinding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppInstallationProviderBinding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider_key": obj.get("provider_key"),
            "oauth_provider_id": obj.get("oauth_provider_id"),
            "oauth_provider_name": obj.get("oauth_provider_name")
        })
        return _obj


