# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260901.052906Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.app_scaffold_progress_status import AppScaffoldProgressStatus
from vertesia_client.openapi.models.start_app_build_response import StartAppBuildResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AppScaffoldProgress(BaseModel):
    """
    AppScaffoldProgress
    """ # noqa: E501
    status: AppScaffoldProgressStatus
    step: StrictStr
    app_id: Optional[StrictStr] = None
    app_record_id: Optional[StrictStr] = None
    installation_id: Optional[StrictStr] = None
    git_url: Optional[StrictStr] = None
    files: Optional[Union[StrictFloat, StrictInt]] = None
    initial_version_build: Optional[StartAppBuildResponse] = None
    error: Optional[StrictStr] = None
    error_details: Optional[List[StrictStr]] = None
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["status", "step", "app_id", "app_record_id", "installation_id", "git_url", "files", "initial_version_build", "error", "error_details", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppScaffoldProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of initial_version_build
        if self.initial_version_build:
            _dict['initial_version_build'] = self.initial_version_build.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppScaffoldProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "step": obj.get("step"),
            "app_id": obj.get("app_id"),
            "app_record_id": obj.get("app_record_id"),
            "installation_id": obj.get("installation_id"),
            "git_url": obj.get("git_url"),
            "files": obj.get("files"),
            "initial_version_build": StartAppBuildResponse.from_dict(obj["initial_version_build"]) if obj.get("initial_version_build") is not None else None,
            "error": obj.get("error"),
            "error_details": obj.get("error_details"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


