# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationStripOptions(BaseModel):
    """
    Configuration for stripping large data from conversation history to prevent JSON serialization issues and reduce storage bloat.
    """ # noqa: E501
    images_after_turns: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of turns to keep images before stripping them. - 0: Strip images immediately after each turn - N > 0: Keep images for N turns before stripping (default: 5) - Infinity: Never strip images")
    text_max_tokens: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum tokens for text content before truncation. Text content exceeding this limit will be truncated with a marker. Uses ~4 characters per token estimate.")
    heartbeats_after_turns: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of turns to keep heartbeat messages before stripping them. Heartbeat messages are periodic workstream status updates wrapped in `<heartbeat>...</heartbeat>` tags that clutter conversation history. - 0: Strip heartbeats immediately after each turn - 1 (default): Keep only the most recent heartbeat - N > 0: Keep heartbeats for N turns before stripping - Infinity: Never strip heartbeats")
    __properties: ClassVar[List[str]] = ["images_after_turns", "text_max_tokens", "heartbeats_after_turns"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationStripOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationStripOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "images_after_turns": obj.get("images_after_turns"),
            "text_max_tokens": obj.get("text_max_tokens"),
            "heartbeats_after_turns": obj.get("heartbeats_after_turns")
        })
        return _obj


