# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vertesia_client.openapi.models.available_skill import AvailableSkill
from vertesia_client.openapi.models.completion_result import CompletionResult
from vertesia_client.openapi.models.conversation_state_end_conversation import ConversationStateEndConversation
from vertesia_client.openapi.models.conversation_strip_options import ConversationStripOptions
from vertesia_client.openapi.models.execution_run_doc_ref import ExecutionRunDocRef
from vertesia_client.openapi.models.execution_token_usage import ExecutionTokenUsage
from vertesia_client.openapi.models.pending_mcp_connection import PendingMcpConnection
from vertesia_client.openapi.models.plan import Plan
from vertesia_client.openapi.models.resolved_interaction_execution_info import ResolvedInteractionExecutionInfo
from vertesia_client.openapi.models.stateless_execution_options import StatelessExecutionOptions
from vertesia_client.openapi.models.tool_activation_metadata import ToolActivationMetadata
from vertesia_client.openapi.models.tool_reference import ToolReference
from vertesia_client.openapi.models.tool_use import ToolUse
from vertesia_client.openapi.models.used_skill import UsedSkill
from vertesia_client.openapi.models.user_channel import UserChannel
from vertesia_client.openapi.models.workflow_ancestor import WorkflowAncestor
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationState(BaseModel):
    """
    Conversation state passed between workflow activities. Contains all context needed to continue a multi-turn agent conversation.
    """ # noqa: E501
    run: ExecutionRunDocRef = Field(description="A reference to the run that started the conversation")
    environment: StrictStr = Field(description="The execution environment with provider info for LLM calls.")
    options: StatelessExecutionOptions = Field(description="The options to use on the next call.")
    tool_use: Optional[List[ToolUse]] = Field(default=None, description="The tools to call next.")
    output: List[CompletionResult] = Field(description="The output of the this conversation step")
    token_usage: Optional[ExecutionTokenUsage] = Field(default=None, description="The token usage of the this conversation step")
    parent: Optional[WorkflowAncestor] = Field(default=None, description="If a sub workflow execution, contains the parent's info")
    ancestors: List[WorkflowAncestor] = Field(description="Full ancestry chain from root to immediate parent (for hierarchical aggregation)")
    task_id: Optional[StrictStr] = Field(default=None, description="If part of a larger agentic workflow, task id of this task")
    plan: Optional[Plan] = Field(default=None, description="Stores the most recent plan for reference by plan-related tools")
    debug: Optional[StrictBool] = Field(default=None, description="Debug mode (more logs and persisted artifacts)")
    strip_options: Optional[ConversationStripOptions] = Field(default=None, description="Configuration for stripping large data from conversation history. Passed to llumiverse ExecutionOptions.stripImagesAfterTurns.")
    conversation_artifacts_base_url: Optional[StrictStr] = Field(default=None, description="Conversation artifacts base url")
    tool_reference: Optional[ToolReference] = Field(default=None, description="Reference to tools stored in GCP instead of embedding full tool definitions")
    active_tool_names: Optional[List[StrictStr]] = Field(default=None, description="Names of currently active tools (base + unlocked). Tool definitions loaded from tool_reference.")
    pinned_tool_names: Optional[List[StrictStr]] = Field(default=None, description="Active tools that should not be evicted by bounded active-tool pruning.")
    tool_activation_metadata: Optional[Dict[str, ToolActivationMetadata]] = Field(default=None, description="Activation and usage metadata for tools seen during the conversation. Used to keep the active tool set bounded without losing recovery context.")
    used_skills: Optional[List[UsedSkill]] = Field(default=None, description="Skills that have been used in this conversation (for auto-syncing scripts and package installation)")
    available_skills: Optional[List[AvailableSkill]] = Field(default=None, description="All available skills from registered tool collections (for upfront hydration in sandbox)")
    streaming_enabled: Optional[StrictBool] = Field(default=None, description="Whether to stream LLM responses to Redis (cached from project config)")
    user_channels: Optional[List[UserChannel]] = Field(default=None, description="Active communication channels with their current state. Channels can be updated as conversation progresses (e.g., email threading info).")
    resolved_interaction: Optional[ResolvedInteractionExecutionInfo] = Field(default=None, description="The resolved interaction execution info. Contains interaction ID, name, version, and environment details.", alias="resolvedInteraction")
    end_conversation: Optional[ConversationStateEndConversation] = None
    unlocked_tools: Optional[List[StrictStr]] = Field(default=None, description="Tools that have been unlocked by skills during the conversation. These tools were initially hidden (default: false) but became available when a skill with tools was called.")
    latest_activity_id: Optional[StrictStr] = Field(default=None, description="Activity ID from the latest LLM call (for deduplication with streamed content). Set by streamToRedis when completing async activities.")
    latest_streaming_id: Optional[StrictStr] = Field(default=None, description="Stable streaming ID from the latest LLM call. Unlike Temporal activity IDs, this is scoped to the concrete workflow run that produced the stream, so it remains safe across continue-as-new.")
    skill_tool_map: Optional[Dict[str, List[StrictStr]]] = Field(default=None, description="Mapping of skill names to their related tools. When a skill is called, its related tools are added to unlocked_tools.")
    disabled_mcp_collections: Optional[List[StrictStr]] = Field(default=None, description="Denylist of MCP tool-collection ids deactivated for this conversation. `undefined`/empty means all installed/connected MCP collections are active. Updated mid-conversation via the MCP config signal; consumed when tools are re-discovered.")
    pending_mcp_connections: Optional[List[PendingMcpConnection]] = Field(default=None, description="MCP servers that are active (not disabled) and accessible to the user but not yet OAuth-connected. Surfaced to the agent (via discover_tools) so it can offer to connect.")
    active_activity_group_id: Optional[StrictStr] = Field(default=None, description="Current activity group ID for internal tool-execution progress messages. All updates emitted during one tool-execution cycle should share this ID.")
    finish_reason: Optional[StrictStr] = Field(default=None, description="LLM stop reason from the latest call (e.g., \"stop\", \"length\", \"tool_use\")")
    agent_run_id: Optional[StrictStr] = Field(default=None, description="The AgentRun ID (MongoDB _id) that owns this conversation. Used for artifact storage paths: agents/{agent_run_id}/ Undefined for legacy workflows started before the AgentRun system.")
    launch_id: Optional[StrictStr] = Field(default=None, description="For workstreams: the launch ID assigned by the parent workflow. When set, artifacts are stored under agents/{agent_run_id}/workstreams/{launch_id}/ to consolidate all artifacts under the parent agent run.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["run", "environment", "options", "tool_use", "output", "token_usage", "parent", "ancestors", "task_id", "plan", "debug", "strip_options", "conversation_artifacts_base_url", "tool_reference", "active_tool_names", "pinned_tool_names", "tool_activation_metadata", "used_skills", "available_skills", "streaming_enabled", "user_channels", "resolvedInteraction", "end_conversation", "unlocked_tools", "latest_activity_id", "latest_streaming_id", "skill_tool_map", "disabled_mcp_collections", "pending_mcp_connections", "active_activity_group_id", "finish_reason", "agent_run_id", "launch_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of run
        if self.run:
            _dict['run'] = self.run.to_dict()
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tool_use (list)
        _items = []
        if self.tool_use:
            for _item_tool_use in self.tool_use:
                if _item_tool_use:
                    _items.append(_item_tool_use.to_dict())
            _dict['tool_use'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in output (list)
        _items = []
        if self.output:
            for _item_output in self.output:
                if _item_output:
                    _items.append(_item_output.to_dict())
            _dict['output'] = _items
        # override the default output from pydantic by calling `to_dict()` of token_usage
        if self.token_usage:
            _dict['token_usage'] = self.token_usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ancestors (list)
        _items = []
        if self.ancestors:
            for _item_ancestors in self.ancestors:
                if _item_ancestors:
                    _items.append(_item_ancestors.to_dict())
            _dict['ancestors'] = _items
        # override the default output from pydantic by calling `to_dict()` of plan
        if self.plan:
            _dict['plan'] = self.plan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of strip_options
        if self.strip_options:
            _dict['strip_options'] = self.strip_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tool_reference
        if self.tool_reference:
            _dict['tool_reference'] = self.tool_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in tool_activation_metadata (dict)
        _field_dict = {}
        if self.tool_activation_metadata:
            for _key_tool_activation_metadata in self.tool_activation_metadata:
                if self.tool_activation_metadata[_key_tool_activation_metadata]:
                    _field_dict[_key_tool_activation_metadata] = self.tool_activation_metadata[_key_tool_activation_metadata].to_dict()
            _dict['tool_activation_metadata'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in used_skills (list)
        _items = []
        if self.used_skills:
            for _item_used_skills in self.used_skills:
                if _item_used_skills:
                    _items.append(_item_used_skills.to_dict())
            _dict['used_skills'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_skills (list)
        _items = []
        if self.available_skills:
            for _item_available_skills in self.available_skills:
                if _item_available_skills:
                    _items.append(_item_available_skills.to_dict())
            _dict['available_skills'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in user_channels (list)
        _items = []
        if self.user_channels:
            for _item_user_channels in self.user_channels:
                if _item_user_channels:
                    _items.append(_item_user_channels.to_dict())
            _dict['user_channels'] = _items
        # override the default output from pydantic by calling `to_dict()` of resolved_interaction
        if self.resolved_interaction:
            _dict['resolvedInteraction'] = self.resolved_interaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of end_conversation
        if self.end_conversation:
            _dict['end_conversation'] = self.end_conversation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in pending_mcp_connections (list)
        _items = []
        if self.pending_mcp_connections:
            for _item_pending_mcp_connections in self.pending_mcp_connections:
                if _item_pending_mcp_connections:
                    _items.append(_item_pending_mcp_connections.to_dict())
            _dict['pending_mcp_connections'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "run": ExecutionRunDocRef.from_dict(obj["run"]) if obj.get("run") is not None else None,
            "environment": obj.get("environment"),
            "options": StatelessExecutionOptions.from_dict(obj["options"]) if obj.get("options") is not None else None,
            "tool_use": [ToolUse.from_dict(_item) for _item in obj["tool_use"]] if obj.get("tool_use") is not None else None,
            "output": [CompletionResult.from_dict(_item) for _item in obj["output"]] if obj.get("output") is not None else None,
            "token_usage": ExecutionTokenUsage.from_dict(obj["token_usage"]) if obj.get("token_usage") is not None else None,
            "parent": WorkflowAncestor.from_dict(obj["parent"]) if obj.get("parent") is not None else None,
            "ancestors": [WorkflowAncestor.from_dict(_item) for _item in obj["ancestors"]] if obj.get("ancestors") is not None else None,
            "task_id": obj.get("task_id"),
            "plan": Plan.from_dict(obj["plan"]) if obj.get("plan") is not None else None,
            "debug": obj.get("debug"),
            "strip_options": ConversationStripOptions.from_dict(obj["strip_options"]) if obj.get("strip_options") is not None else None,
            "conversation_artifacts_base_url": obj.get("conversation_artifacts_base_url"),
            "tool_reference": ToolReference.from_dict(obj["tool_reference"]) if obj.get("tool_reference") is not None else None,
            "active_tool_names": obj.get("active_tool_names"),
            "pinned_tool_names": obj.get("pinned_tool_names"),
            "tool_activation_metadata": dict(
                (_k, ToolActivationMetadata.from_dict(_v))
                for _k, _v in obj["tool_activation_metadata"].items()
            )
            if obj.get("tool_activation_metadata") is not None
            else None,
            "used_skills": [UsedSkill.from_dict(_item) for _item in obj["used_skills"]] if obj.get("used_skills") is not None else None,
            "available_skills": [AvailableSkill.from_dict(_item) for _item in obj["available_skills"]] if obj.get("available_skills") is not None else None,
            "streaming_enabled": obj.get("streaming_enabled"),
            "user_channels": [UserChannel.from_dict(_item) for _item in obj["user_channels"]] if obj.get("user_channels") is not None else None,
            "resolvedInteraction": ResolvedInteractionExecutionInfo.from_dict(obj["resolvedInteraction"]) if obj.get("resolvedInteraction") is not None else None,
            "end_conversation": ConversationStateEndConversation.from_dict(obj["end_conversation"]) if obj.get("end_conversation") is not None else None,
            "unlocked_tools": obj.get("unlocked_tools"),
            "latest_activity_id": obj.get("latest_activity_id"),
            "latest_streaming_id": obj.get("latest_streaming_id"),
            "skill_tool_map": obj.get("skill_tool_map"),
            "disabled_mcp_collections": obj.get("disabled_mcp_collections"),
            "pending_mcp_connections": [PendingMcpConnection.from_dict(_item) for _item in obj["pending_mcp_connections"]] if obj.get("pending_mcp_connections") is not None else None,
            "active_activity_group_id": obj.get("active_activity_group_id"),
            "finish_reason": obj.get("finish_reason"),
            "agent_run_id": obj.get("agent_run_id"),
            "launch_id": obj.get("launch_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


