# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional, Union
from vertesia_client.openapi.models.file_processing_status import FileProcessingStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationFile(BaseModel):
    """
    Represents a file being processed in a conversation workflow.
    """ # noqa: E501
    id: StrictStr = Field(description="Unique ID for tracking this file (generated client-side)")
    name: StrictStr = Field(description="Original filename")
    content_type: StrictStr = Field(description="MIME type")
    size: Union[StrictFloat, StrictInt] = Field(description="Size in bytes")
    status: FileProcessingStatus = Field(description="Current processing status")
    artifact_path: Optional[StrictStr] = Field(default=None, description="Artifact path (e.g., \"files/document.pdf\") - set after upload")
    reference: Optional[StrictStr] = Field(default=None, description="Full artifact reference URI (e.g., \"artifact:files/document.pdf\")")
    md_path: Optional[StrictStr] = Field(default=None, description="Path to extracted text markdown (e.g., \"files/document.pdf.md\")")
    text_extracted: Optional[StrictBool] = Field(default=None, description="Whether text extraction completed successfully")
    error: Optional[StrictStr] = Field(default=None, description="Error message if status is ERROR")
    started_at: Union[StrictFloat, StrictInt] = Field(description="Timestamp when upload started")
    completed_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Timestamp when processing completed")
    __properties: ClassVar[List[str]] = ["id", "name", "content_type", "size", "status", "artifact_path", "reference", "md_path", "text_extracted", "error", "started_at", "completed_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "content_type": obj.get("content_type"),
            "size": obj.get("size"),
            "status": obj.get("status"),
            "artifact_path": obj.get("artifact_path"),
            "reference": obj.get("reference"),
            "md_path": obj.get("md_path"),
            "text_extracted": obj.get("text_extracted"),
            "error": obj.get("error"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at")
        })
        return _obj


