# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from vertesia_client.openapi.models.audio_metadata import AudioMetadata
from vertesia_client.openapi.models.content_metadata import ContentMetadata
from vertesia_client.openapi.models.document_metadata import DocumentMetadata
from vertesia_client.openapi.models.image_metadata import ImageMetadata
from vertesia_client.openapi.models.video_metadata import VideoMetadata
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

CREATECONTENTOBJECTPAYLOADMETADATA_ANY_OF_SCHEMAS = ["AudioMetadata", "ContentMetadata", "DocumentMetadata", "ImageMetadata", "VideoMetadata"]

class CreateContentObjectPayloadMetadata(BaseModel):
    """
    Technical metadata of the object
    """

    # data type: VideoMetadata
    anyof_schema_1_validator: Optional[VideoMetadata] = None
    # data type: AudioMetadata
    anyof_schema_2_validator: Optional[AudioMetadata] = None
    # data type: ImageMetadata
    anyof_schema_3_validator: Optional[ImageMetadata] = None
    # data type: DocumentMetadata
    anyof_schema_4_validator: Optional[DocumentMetadata] = None
    # data type: ContentMetadata
    anyof_schema_5_validator: Optional[ContentMetadata] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[AudioMetadata, ContentMetadata, DocumentMetadata, ImageMetadata, VideoMetadata]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "AudioMetadata", "ContentMetadata", "DocumentMetadata", "ImageMetadata", "VideoMetadata" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = CreateContentObjectPayloadMetadata.model_construct()
        error_messages = []
        # validate data type: VideoMetadata
        if not isinstance(v, VideoMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VideoMetadata`")
        else:
            return v

        # validate data type: AudioMetadata
        if not isinstance(v, AudioMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AudioMetadata`")
        else:
            return v

        # validate data type: ImageMetadata
        if not isinstance(v, ImageMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageMetadata`")
        else:
            return v

        # validate data type: DocumentMetadata
        if not isinstance(v, DocumentMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocumentMetadata`")
        else:
            return v

        # validate data type: ContentMetadata
        if not isinstance(v, ContentMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ContentMetadata`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in CreateContentObjectPayloadMetadata with anyOf schemas: AudioMetadata, ContentMetadata, DocumentMetadata, ImageMetadata, VideoMetadata. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[VideoMetadata] = None
        try:
            instance.actual_instance = VideoMetadata.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[AudioMetadata] = None
        try:
            instance.actual_instance = AudioMetadata.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ImageMetadata] = None
        try:
            instance.actual_instance = ImageMetadata.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[DocumentMetadata] = None
        try:
            instance.actual_instance = DocumentMetadata.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[ContentMetadata] = None
        try:
            instance.actual_instance = ContentMetadata.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreateContentObjectPayloadMetadata with anyOf schemas: AudioMetadata, ContentMetadata, DocumentMetadata, ImageMetadata, VideoMetadata. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AudioMetadata, ContentMetadata, DocumentMetadata, ImageMetadata, VideoMetadata]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


