# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vertesia_client.openapi.models.column_layout import ColumnLayout
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateContentObjectTypePayload(BaseModel):
    """
    CreateContentObjectTypePayload
    """ # noqa: E501
    is_chunkable: Optional[StrictBool] = None
    table_layout: Optional[List[ColumnLayout]] = Field(default=None, description="This is only included in ContentObjectTypeItem if explicitly requested It is always included in ContentObjectType")
    object_schema: Optional[Dict[str, Any]] = Field(default=None, description="this is only included in ContentObjectTypeItem if explicitly requested It is always included in ContentObjectType")
    strict_mode: Optional[StrictBool] = Field(default=None, description="Determines if the content will be validated against the object schema a generation time and save/update time.")
    name: StrictStr = Field(description="Human-readable name or title")
    description: Optional[StrictStr] = Field(default=None, description="Optional detailed description of the object")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Optional array of categorization tags")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["is_chunkable", "table_layout", "object_schema", "strict_mode", "name", "description", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateContentObjectTypePayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in table_layout (list)
        _items = []
        if self.table_layout:
            for _item_table_layout in self.table_layout:
                if _item_table_layout:
                    _items.append(_item_table_layout.to_dict())
            _dict['table_layout'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateContentObjectTypePayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_chunkable": obj.get("is_chunkable"),
            "table_layout": [ColumnLayout.from_dict(_item) for _item in obj["table_layout"]] if obj.get("table_layout") is not None else None,
            "object_schema": obj.get("object_schema"),
            "strict_mode": obj.get("strict_mode"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "tags": obj.get("tags")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


