# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DashboardVersionItem(BaseModel):
    """
    Summary view of a dashboard version (for listings).
    """ # noqa: E501
    id: StrictStr = Field(description="Version ID")
    dashboard_id: StrictStr = Field(description="Parent dashboard ID")
    version_number: Union[StrictFloat, StrictInt] = Field(description="Version number")
    message: StrictStr = Field(description="Commit message")
    is_current: StrictBool = Field(description="Whether this is the current version")
    is_snapshot: StrictBool = Field(description="Whether this is a named snapshot")
    snapshot_name: Optional[StrictStr] = Field(default=None, description="Snapshot name (if is_snapshot)")
    panel_count: Union[StrictFloat, StrictInt] = Field(description="Number of panels in this version")
    query_count: Union[StrictFloat, StrictInt] = Field(description="Number of queries in this version")
    created_at: StrictStr = Field(description="Creation timestamp")
    created_by: Optional[StrictStr] = Field(default=None, description="User/agent who created")
    __properties: ClassVar[List[str]] = ["id", "dashboard_id", "version_number", "message", "is_current", "is_snapshot", "snapshot_name", "panel_count", "query_count", "created_at", "created_by"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardVersionItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardVersionItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "dashboard_id": obj.get("dashboard_id"),
            "version_number": obj.get("version_number"),
            "message": obj.get("message"),
            "is_current": obj.get("is_current"),
            "is_snapshot": obj.get("is_snapshot"),
            "snapshot_name": obj.get("snapshot_name"),
            "panel_count": obj.get("panel_count"),
            "query_count": obj.get("query_count"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by")
        })
        return _obj


