# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from vertesia_client.openapi.models.data_relationship_for_ai import DataRelationshipForAI
from vertesia_client.openapi.models.data_table_for_ai import DataTableForAI
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DataSchemaForAI(BaseModel):
    """
    Simplified schema representation optimized for AI agent consumption. Provides semantic context for understanding the data model.
    """ # noqa: E501
    schema_format: StrictStr
    name: StrictStr = Field(description="Store name")
    version: StrictStr = Field(description="Schema version")
    description: Optional[StrictStr] = Field(default=None, description="Schema description")
    tables: Dict[str, DataTableForAI] = Field(description="Tables by name")
    relationships: List[DataRelationshipForAI] = Field(description="Relationships")
    __properties: ClassVar[List[str]] = ["schema_format", "name", "version", "description", "tables", "relationships"]

    @field_validator('schema_format')
    def schema_format_validate_enum(cls, value):
        """Validates the enum"""
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSchemaForAI from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in tables (dict)
        _field_dict = {}
        if self.tables:
            for _key_tables in self.tables:
                if self.tables[_key_tables]:
                    _field_dict[_key_tables] = self.tables[_key_tables].to_dict()
            _dict['tables'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in relationships (list)
        _items = []
        if self.relationships:
            for _item_relationships in self.relationships:
                if _item_relationships:
                    _items.append(_item_relationships.to_dict())
            _dict['relationships'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSchemaForAI from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema_format": obj.get("schema_format"),
            "name": obj.get("name"),
            "version": obj.get("version"),
            "description": obj.get("description"),
            "tables": dict(
                (_k, DataTableForAI.from_dict(_v))
                for _k, _v in obj["tables"].items()
            )
            if obj.get("tables") is not None
            else None,
            "relationships": [DataRelationshipForAI.from_dict(_item) for _item in obj["relationships"]] if obj.get("relationships") is not None else None
        })
        return _obj


