# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.content_nature_document import ContentNatureDocument
from vertesia_client.openapi.models.document_metadata_content_processor import DocumentMetadataContentProcessor
from vertesia_client.openapi.models.generation_run_metadata import GenerationRunMetadata
from vertesia_client.openapi.models.location import Location
from vertesia_client.openapi.models.rendition import Rendition
from vertesia_client.openapi.models.text_section import TextSection
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DocumentMetadata(BaseModel):
    """
    DocumentMetadata
    """ # noqa: E501
    type: ContentNatureDocument
    size: Optional[Union[StrictFloat, StrictInt]] = None
    languages: Optional[List[StrictStr]] = None
    location: Optional[Location] = None
    generation_runs: Optional[List[GenerationRunMetadata]] = None
    etag: Optional[StrictStr] = None
    renditions: Optional[List[Rendition]] = None
    page_count: Optional[Union[StrictFloat, StrictInt]] = None
    content_processor: Optional[DocumentMetadataContentProcessor] = None
    sections: Optional[List[TextSection]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "size", "languages", "location", "generation_runs", "etag", "renditions", "page_count", "content_processor", "sections"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in generation_runs (list)
        _items = []
        if self.generation_runs:
            for _item_generation_runs in self.generation_runs:
                if _item_generation_runs:
                    _items.append(_item_generation_runs.to_dict())
            _dict['generation_runs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in renditions (list)
        _items = []
        if self.renditions:
            for _item_renditions in self.renditions:
                if _item_renditions:
                    _items.append(_item_renditions.to_dict())
            _dict['renditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of content_processor
        if self.content_processor:
            _dict['content_processor'] = self.content_processor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sections (list)
        _items = []
        if self.sections:
            for _item_sections in self.sections:
                if _item_sections:
                    _items.append(_item_sections.to_dict())
            _dict['sections'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "size": obj.get("size"),
            "languages": obj.get("languages"),
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "generation_runs": [GenerationRunMetadata.from_dict(_item) for _item in obj["generation_runs"]] if obj.get("generation_runs") is not None else None,
            "etag": obj.get("etag"),
            "renditions": [Rendition.from_dict(_item) for _item in obj["renditions"]] if obj.get("renditions") is not None else None,
            "page_count": obj.get("page_count"),
            "content_processor": DocumentMetadataContentProcessor.from_dict(obj["content_processor"]) if obj.get("content_processor") is not None else None,
            "sections": [TextSection.from_dict(_item) for _item in obj["sections"]] if obj.get("sections") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


