# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DriftAnalysisProgress(BaseModel):
    """
    DriftAnalysisProgress
    """ # noqa: E501
    total: Union[StrictFloat, StrictInt]
    processed: Union[StrictFloat, StrictInt]
    missing: Union[StrictFloat, StrictInt]
    stale: Union[StrictFloat, StrictInt]
    status: StrictStr
    current_batch: Union[StrictFloat, StrictInt]
    total_batches: Union[StrictFloat, StrictInt]
    percent_complete: Union[StrictFloat, StrictInt]
    docs_per_second: Union[StrictFloat, StrictInt]
    elapsed_seconds: Union[StrictFloat, StrictInt]
    estimated_seconds_remaining: Optional[Union[StrictFloat, StrictInt]]
    __properties: ClassVar[List[str]] = ["total", "processed", "missing", "stale", "status", "current_batch", "total_batches", "percent_complete", "docs_per_second", "elapsed_seconds", "estimated_seconds_remaining"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DriftAnalysisProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if estimated_seconds_remaining (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_seconds_remaining is None and "estimated_seconds_remaining" in self.model_fields_set:
            _dict['estimated_seconds_remaining'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DriftAnalysisProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "processed": obj.get("processed"),
            "missing": obj.get("missing"),
            "stale": obj.get("stale"),
            "status": obj.get("status"),
            "current_batch": obj.get("current_batch"),
            "total_batches": obj.get("total_batches"),
            "percent_complete": obj.get("percent_complete"),
            "docs_per_second": obj.get("docs_per_second"),
            "elapsed_seconds": obj.get("elapsed_seconds"),
            "estimated_seconds_remaining": obj.get("estimated_seconds_remaining")
        })
        return _obj


