# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from vertesia_client.openapi.models.dsl_activity_step import DSLActivityStep
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DSLWORKFLOWSTEP_ONE_OF_SCHEMAS = ["DSLActivityStep", "DSLChildWorkflowStep"]

class DSLWorkflowStep(BaseModel):
    """
    DSLWorkflowStep
    """
    # data type: DSLActivityStep
    oneof_schema_1_validator: Optional[DSLActivityStep] = None
    # data type: DSLChildWorkflowStep
    oneof_schema_2_validator: Optional[DSLChildWorkflowStep] = None
    actual_instance: Optional[Union[DSLActivityStep, DSLChildWorkflowStep]] = None
    one_of_schemas: Set[str] = { "DSLActivityStep", "DSLChildWorkflowStep" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DSLWorkflowStep.model_construct()
        error_messages = []
        match = 0
        # validate data type: DSLActivityStep
        if not isinstance(v, DSLActivityStep):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DSLActivityStep`")
        else:
            match += 1
        # validate data type: DSLChildWorkflowStep
        if not isinstance(v, DSLChildWorkflowStep):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DSLChildWorkflowStep`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DSLWorkflowStep with oneOf schemas: DSLActivityStep, DSLChildWorkflowStep. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DSLWorkflowStep with oneOf schemas: DSLActivityStep, DSLChildWorkflowStep. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DSLActivityStep
        try:
            instance.actual_instance = DSLActivityStep.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DSLChildWorkflowStep
        try:
            instance.actual_instance = DSLChildWorkflowStep.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DSLWorkflowStep with oneOf schemas: DSLActivityStep, DSLChildWorkflowStep. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DSLWorkflowStep with oneOf schemas: DSLActivityStep, DSLChildWorkflowStep. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DSLActivityStep, DSLChildWorkflowStep]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from vertesia_client.openapi.models.dsl_child_workflow_step import DSLChildWorkflowStep
# TODO: Rewrite to not use raise_errors
DSLWorkflowStep.model_rebuild(raise_errors=False)

