# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.embeddings_api_source import EmbeddingsApiSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmbeddingsApiVideoInput(BaseModel):
    """
    EmbeddingsApiVideoInput
    """ # noqa: E501
    type: StrictStr
    source: EmbeddingsApiSource
    start_sec: Optional[Union[StrictFloat, StrictInt]] = None
    length_sec: Optional[Union[StrictFloat, StrictInt]] = None
    interval_sec: Optional[Union[StrictFloat, StrictInt]] = None
    use_fixed_length_sec: Optional[StrictBool] = None
    min_clip_sec: Optional[Union[StrictFloat, StrictInt]] = None
    embedding_option: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["type", "source", "start_sec", "length_sec", "interval_sec", "use_fixed_length_sec", "min_clip_sec", "embedding_option"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        return value

    @field_validator('embedding_option')
    def embedding_option_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['visual-text', 'visual-image', 'audio']):
                raise ValueError("each list item must be one of ('visual-text', 'visual-image', 'audio')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmbeddingsApiVideoInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmbeddingsApiVideoInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "source": EmbeddingsApiSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "start_sec": obj.get("start_sec"),
            "length_sec": obj.get("length_sec"),
            "interval_sec": obj.get("interval_sec"),
            "use_fixed_length_sec": obj.get("use_fixed_length_sec"),
            "min_clip_sec": obj.get("min_clip_sec"),
            "embedding_option": obj.get("embedding_option")
        })
        return _obj


