# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.embeddings_status_response_vector_index import EmbeddingsStatusResponseVectorIndex
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmbeddingsStatusResponse(BaseModel):
    """
    EmbeddingsStatusResponse
    """ # noqa: E501
    status: StrictStr
    embedding_runs_in_progress: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="embeddingRunsInProgress")
    total_indexable_objects: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalIndexableObjects")
    embeddings_models: Optional[List[StrictStr]] = Field(default=None, alias="embeddingsModels")
    objects_with_embeddings: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="objectsWithEmbeddings")
    vector_index: EmbeddingsStatusResponseVectorIndex = Field(alias="vectorIndex")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["status", "embeddingRunsInProgress", "totalIndexableObjects", "embeddingsModels", "objectsWithEmbeddings", "vectorIndex"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmbeddingsStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of vector_index
        if self.vector_index:
            _dict['vectorIndex'] = self.vector_index.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmbeddingsStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "embeddingRunsInProgress": obj.get("embeddingRunsInProgress"),
            "totalIndexableObjects": obj.get("totalIndexableObjects"),
            "embeddingsModels": obj.get("embeddingsModels"),
            "objectsWithEmbeddings": obj.get("objectsWithEmbeddings"),
            "vectorIndex": EmbeddingsStatusResponseVectorIndex.from_dict(obj["vectorIndex"]) if obj.get("vectorIndex") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


