# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, Optional
from vertesia_client.openapi.models.event_ingest_signature_algorithm import EventIngestSignatureAlgorithm
from vertesia_client.openapi.models.event_ingest_signature_encoding import EventIngestSignatureEncoding
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EventIngestSignatureConfig(BaseModel):
    """
    Optional HMAC signature verification for an ingest channel. When configured, the server recomputes `HMAC(algorithm, signing_secret, rawBody)` and compares it (timing-safe) to the value in `header`, after stripping `prefix`. Covers GitHub-style `X-Hub-Signature-256: sha256=<hex>` and a plain Salesforce Apex-callout HMAC.
    """ # noqa: E501
    header: StrictStr = Field(description="Request header carrying the signature, e.g. `x-hub-signature-256`.")
    algorithm: Optional[EventIngestSignatureAlgorithm] = None
    encoding: Optional[EventIngestSignatureEncoding] = None
    prefix: Optional[StrictStr] = Field(default=None, description="Literal prefix stripped from the header value before comparison, e.g. `sha256=`.")
    has_secret: Optional[StrictBool] = Field(default=None, description="Server-managed: whether a signing secret is stored for this channel.")
    secret_hint: Optional[StrictStr] = Field(default=None, description="Server-managed: label/hint of the stored signing secret.")
    __properties: ClassVar[List[str]] = ["header", "algorithm", "encoding", "prefix", "has_secret", "secret_hint"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventIngestSignatureConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventIngestSignatureConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "header": obj.get("header"),
            "algorithm": obj.get("algorithm"),
            "encoding": obj.get("encoding"),
            "prefix": obj.get("prefix"),
            "has_secret": obj.get("has_secret"),
            "secret_hint": obj.get("secret_hint")
        })
        return _obj


