# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vertesia_client.openapi.models.event_ingest_resource_rule import EventIngestResourceRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EventIngestTransform(BaseModel):
    """
    Declarative mapping from a raw third-party webhook body to platform event fields, for senders that cannot shape their payload (GitHub, Slack, DocuSign, Salesforce, ...). Each `*_path` is a dot-path into the JSON body (array indices supported, e.g. `commits.0.id`). Extracted values override the channel defaults; the full raw body is always preserved under `event.details.payload`.
    """ # noqa: E501
    action_path: Optional[StrictStr] = Field(default=None, description="Dot-path to the value used as `event.action`, e.g. `event.type`.")
    resource_type_path: Optional[StrictStr] = Field(default=None, description="Dot-path to the value used as `event.resource_type`.")
    resource_id_path: Optional[StrictStr] = Field(default=None, description="Dot-path to the value used as `event.resource_id`.")
    event_type_header: Optional[StrictStr] = Field(default=None, description="Request **header** carrying the event family (e.g. GitHub's `x-github-event`), captured into `event.details.event_type`. Lets subscriptions and `resource_rules` discriminate event shapes when one channel receives heterogeneous payloads whose `action` alone is ambiguous (e.g. `created` for both an issue comment and a PR review comment).")
    resource_rules: Optional[List[EventIngestResourceRule]] = Field(default=None, description="Ordered conditional rules for `resource_type` + `resource_id` (first match wins). Used when a single `resource_id_path` can't serve every payload shape. Falls back to `resource_type_path` / `resource_id_path` / channel defaults when no rule matches.")
    idempotency_key_path: Optional[StrictStr] = Field(default=None, description="Dot-path to a deduplication key (same semantics as `idempotency_key`).")
    idempotency_key_header: Optional[StrictStr] = Field(default=None, description="Request **header** to use as the deduplication key when the body has no stable per-delivery id — e.g. GitHub App's `x-github-delivery`, unique per delivery for all event types, which is the only reliable dedup key when one App webhook delivers heterogeneous payloads (issues + comments) to a single channel. Lower precedence than `idempotency_key_path`.")
    timestamp_path: Optional[StrictStr] = Field(default=None, description="Dot-path to an ISO 8601 event timestamp.")
    static_details: Optional[Dict[str, Any]] = Field(default=None, description="Static fields merged into `event.details`.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["action_path", "resource_type_path", "resource_id_path", "event_type_header", "resource_rules", "idempotency_key_path", "idempotency_key_header", "timestamp_path", "static_details"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventIngestTransform from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in resource_rules (list)
        _items = []
        if self.resource_rules:
            for _item_resource_rules in self.resource_rules:
                if _item_resource_rules:
                    _items.append(_item_resource_rules.to_dict())
            _dict['resource_rules'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventIngestTransform from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action_path": obj.get("action_path"),
            "resource_type_path": obj.get("resource_type_path"),
            "resource_id_path": obj.get("resource_id_path"),
            "event_type_header": obj.get("event_type_header"),
            "resource_rules": [EventIngestResourceRule.from_dict(_item) for _item in obj["resource_rules"]] if obj.get("resource_rules") is not None else None,
            "idempotency_key_path": obj.get("idempotency_key_path"),
            "idempotency_key_header": obj.get("idempotency_key_header"),
            "timestamp_path": obj.get("timestamp_path"),
            "static_details": obj.get("static_details")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


