# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, Optional
from vertesia_client.openapi.models.config_modes import ConfigModes
from vertesia_client.openapi.models.model_options import ModelOptions
from vertesia_client.openapi.models.run_data_storage_level import RunDataStorageLevel
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InteractionExecutionConfiguration(BaseModel):
    """
    InteractionExecutionConfiguration
    """ # noqa: E501
    id: Optional[StrictStr] = None
    environment: Optional[StrictStr] = None
    model: Optional[StrictStr] = None
    do_validate: Optional[StrictBool] = None
    run_data: Optional[RunDataStorageLevel] = None
    config_mode: Optional[ConfigModes] = Field(default=None, alias="configMode")
    model_options: Optional[ModelOptions] = None
    __properties: ClassVar[List[str]] = ["id", "environment", "model", "do_validate", "run_data", "configMode", "model_options"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InteractionExecutionConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model_options
        if self.model_options:
            _dict['model_options'] = self.model_options.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InteractionExecutionConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "environment": obj.get("environment"),
            "model": obj.get("model"),
            "do_validate": obj.get("do_validate"),
            "run_data": obj.get("run_data"),
            "configMode": obj.get("configMode"),
            "model_options": ModelOptions.from_dict(obj["model_options"]) if obj.get("model_options") is not None else None
        })
        return _obj


