# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional, Union
from vertesia_client.openapi.models.conversation_activity_state import ConversationActivityState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListWorkflowRunsPayload(BaseModel):
    """
    ListWorkflowRunsPayload
    """ # noqa: E501
    document_id: Optional[StrictStr] = Field(default=None, description="The document ID passed to a workflow run.")
    event_name: Optional[StrictStr] = Field(default=None, description="The event name that triggered the workflow.")
    rule_id: Optional[StrictStr] = Field(default=None, description="Legacy workflow rule ID filter, when applicable.")
    start: Optional[StrictStr] = Field(default=None, description="The start time for filtering workflow runs.")
    end: Optional[StrictStr] = Field(default=None, description="The end time for filtering workflow runs.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the workflow run.")
    search_term: Optional[StrictStr] = Field(default=None, description="search term to filter on workflow id and run id")
    initiated_by: Optional[StrictStr] = Field(default=None, description="The user or service account that initiated the workflow run.")
    interaction: Optional[StrictStr] = Field(default=None, description="The interaction name used to filter conversations.")
    query: Optional[StrictStr] = Field(default=None, description="Lucene query string to search for the workflow runs. This is a full text search on the workflow run history.")
    type: Optional[StrictStr] = None
    page_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The maximum number of results to return per page.")
    next_page_token: Optional[StrictStr] = Field(default=None, description="The page token for Temporal pagination.")
    has_reported_errors: Optional[StrictBool] = Field(default=None, description="Filter by whether the workflow has reported errors (TemporalReportedProblems).")
    activity_state: Optional[ConversationActivityState] = Field(default=None, description="Filter by the activity state of the conversation (running or idle).")
    interactive: Optional[StrictBool] = Field(default=None, description="Filter by whether the conversation is interactive.")
    __properties: ClassVar[List[str]] = ["document_id", "event_name", "rule_id", "start", "end", "status", "search_term", "initiated_by", "interaction", "query", "type", "page_size", "next_page_token", "has_reported_errors", "activity_state", "interactive"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListWorkflowRunsPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListWorkflowRunsPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "document_id": obj.get("document_id"),
            "event_name": obj.get("event_name"),
            "rule_id": obj.get("rule_id"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "status": obj.get("status"),
            "search_term": obj.get("search_term"),
            "initiated_by": obj.get("initiated_by"),
            "interaction": obj.get("interaction"),
            "query": obj.get("query"),
            "type": obj.get("type"),
            "page_size": obj.get("page_size"),
            "next_page_token": obj.get("next_page_token"),
            "has_reported_errors": obj.get("has_reported_errors"),
            "activity_state": obj.get("activity_state"),
            "interactive": obj.get("interactive")
        })
        return _obj


