# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PartialRecordAuditAggregationDimensionStringNull(BaseModel):
    """
    PartialRecordAuditAggregationDimensionStringNull
    """ # noqa: E501
    time: Optional[StrictStr] = None
    action: Optional[StrictStr] = None
    resource_type: Optional[StrictStr] = None
    event_category: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    project_id: Optional[StrictStr] = None
    details_pipeline: Optional[StrictStr] = Field(default=None, alias="details.pipeline")
    details_verdict: Optional[StrictStr] = Field(default=None, alias="details.verdict")
    details_workflow_type: Optional[StrictStr] = Field(default=None, alias="details.workflow_type")
    details_rule_id: Optional[StrictStr] = Field(default=None, alias="details.rule_id")
    model: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["time", "action", "resource_type", "event_category", "provider", "project_id", "details.pipeline", "details.verdict", "details.workflow_type", "details.rule_id", "model"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PartialRecordAuditAggregationDimensionStringNull from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if time (nullable) is None
        # and model_fields_set contains the field
        if self.time is None and "time" in self.model_fields_set:
            _dict['time'] = None

        # set to None if action (nullable) is None
        # and model_fields_set contains the field
        if self.action is None and "action" in self.model_fields_set:
            _dict['action'] = None

        # set to None if resource_type (nullable) is None
        # and model_fields_set contains the field
        if self.resource_type is None and "resource_type" in self.model_fields_set:
            _dict['resource_type'] = None

        # set to None if event_category (nullable) is None
        # and model_fields_set contains the field
        if self.event_category is None and "event_category" in self.model_fields_set:
            _dict['event_category'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if details_pipeline (nullable) is None
        # and model_fields_set contains the field
        if self.details_pipeline is None and "details_pipeline" in self.model_fields_set:
            _dict['details.pipeline'] = None

        # set to None if details_verdict (nullable) is None
        # and model_fields_set contains the field
        if self.details_verdict is None and "details_verdict" in self.model_fields_set:
            _dict['details.verdict'] = None

        # set to None if details_workflow_type (nullable) is None
        # and model_fields_set contains the field
        if self.details_workflow_type is None and "details_workflow_type" in self.model_fields_set:
            _dict['details.workflow_type'] = None

        # set to None if details_rule_id (nullable) is None
        # and model_fields_set contains the field
        if self.details_rule_id is None and "details_rule_id" in self.model_fields_set:
            _dict['details.rule_id'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PartialRecordAuditAggregationDimensionStringNull from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "time": obj.get("time"),
            "action": obj.get("action"),
            "resource_type": obj.get("resource_type"),
            "event_category": obj.get("event_category"),
            "provider": obj.get("provider"),
            "project_id": obj.get("project_id"),
            "details.pipeline": obj.get("details.pipeline"),
            "details.verdict": obj.get("details.verdict"),
            "details.workflow_type": obj.get("details.workflow_type"),
            "details.rule_id": obj.get("details.rule_id"),
            "model": obj.get("model")
        })
        return _obj


