# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.node_history_entry import NodeHistoryEntry
from vertesia_client.openapi.models.process_history_ref import ProcessHistoryRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProcessState(BaseModel):
    """
    ProcessState
    """ # noqa: E501
    context: Dict[str, Any]
    current_node: StrictStr
    node_history: List[NodeHistoryEntry]
    node_history_ref: Optional[ProcessHistoryRef] = None
    sequence: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["context", "current_node", "node_history", "node_history_ref", "sequence"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProcessState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in node_history (list)
        _items = []
        if self.node_history:
            for _item_node_history in self.node_history:
                if _item_node_history:
                    _items.append(_item_node_history.to_dict())
            _dict['node_history'] = _items
        # override the default output from pydantic by calling `to_dict()` of node_history_ref
        if self.node_history_ref:
            _dict['node_history_ref'] = self.node_history_ref.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProcessState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context": obj.get("context"),
            "current_node": obj.get("current_node"),
            "node_history": [NodeHistoryEntry.from_dict(_item) for _item in obj["node_history"]] if obj.get("node_history") is not None else None,
            "node_history_ref": ProcessHistoryRef.from_dict(obj["node_history_ref"]) if obj.get("node_history_ref") is not None else None,
            "sequence": obj.get("sequence")
        })
        return _obj


