# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, Optional
from vertesia_client.openapi.models.process_context_definition import ProcessContextDefinition
from vertesia_client.openapi.models.process_definition_format_version import ProcessDefinitionFormatVersion
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProcessDefinitionBody(BaseModel):
    """
    ProcessDefinitionBody
    """ # noqa: E501
    format_version: ProcessDefinitionFormatVersion
    process: StrictStr
    description: Optional[StrictStr] = None
    initial: StrictStr
    model: Optional[StrictStr] = None
    context: ProcessContextDefinition
    nodes: Dict[str, NodeDefinition]
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["format_version", "process", "description", "initial", "model", "context", "nodes", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProcessDefinitionBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in nodes (dict)
        _field_dict = {}
        if self.nodes:
            for _key_nodes in self.nodes:
                if self.nodes[_key_nodes]:
                    _field_dict[_key_nodes] = self.nodes[_key_nodes].to_dict()
            _dict['nodes'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProcessDefinitionBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "format_version": obj.get("format_version"),
            "process": obj.get("process"),
            "description": obj.get("description"),
            "initial": obj.get("initial"),
            "model": obj.get("model"),
            "context": ProcessContextDefinition.from_dict(obj["context"]) if obj.get("context") is not None else None,
            "nodes": dict(
                (_k, NodeDefinition.from_dict(_v))
                for _k, _v in obj["nodes"].items()
            )
            if obj.get("nodes") is not None
            else None,
            "metadata": obj.get("metadata")
        })
        return _obj

from vertesia_client.openapi.models.node_definition import NodeDefinition
# TODO: Rewrite to not use raise_errors
ProcessDefinitionBody.model_rebuild(raise_errors=False)

