# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from vertesia_client.openapi.models.quota_standing_resource import QuotaStandingResource
from vertesia_client.openapi.models.quota_standing_response_admission import QuotaStandingResponseAdmission
from vertesia_client.openapi.models.quota_standing_response_llm import QuotaStandingResponseLlm
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QuotaStandingResponse(BaseModel):
    """
    QuotaStandingResponse
    """ # noqa: E501
    tenant_id: StrictStr
    available: StrictBool = Field(description="False when the limiter store (Redis) was unavailable, so `api`/`admission` are empty because standing could not be read — NOT because there are no limits. Limiters fail open in this case.")
    base_tier: StrictStr = Field(description="Deployment base tier (env QUOTA_BASE_TIER); `default` = the static limits stand.")
    effective_tier: StrictStr = Field(description="Tier used to compute the API limits below: explicit account `quota_tier`, else account_type derived tier, else `base_tier` when the account tier could not be resolved.")
    api: List[QuotaStandingResource] = Field(description="Per-resource API rate-limit standing (effective limits + current usage).")
    admission: QuotaStandingResponseAdmission
    llm: QuotaStandingResponseLlm
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["tenant_id", "available", "base_tier", "effective_tier", "api", "admission", "llm"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuotaStandingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in api (list)
        _items = []
        if self.api:
            for _item_api in self.api:
                if _item_api:
                    _items.append(_item_api.to_dict())
            _dict['api'] = _items
        # override the default output from pydantic by calling `to_dict()` of admission
        if self.admission:
            _dict['admission'] = self.admission.to_dict()
        # override the default output from pydantic by calling `to_dict()` of llm
        if self.llm:
            _dict['llm'] = self.llm.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuotaStandingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenant_id": obj.get("tenant_id"),
            "available": obj.get("available"),
            "base_tier": obj.get("base_tier"),
            "effective_tier": obj.get("effective_tier"),
            "api": [QuotaStandingResource.from_dict(_item) for _item in obj["api"]] if obj.get("api") is not None else None,
            "admission": QuotaStandingResponseAdmission.from_dict(obj["admission"]) if obj.get("admission") is not None else None,
            "llm": QuotaStandingResponseLlm.from_dict(obj["llm"]) if obj.get("llm") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


