# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260901.052906Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from vertesia_client.openapi.models.app_scaffold_module import AppScaffoldModule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StartAppScaffoldRequest(BaseModel):
    """
    StartAppScaffoldRequest
    """ # noqa: E501
    app_id: StrictStr = Field(description="Package name for the new app to create and scaffold. This is not the id of an existing app.")
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    modules: Optional[List[AppScaffoldModule]] = None
    appgen_package_spec: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Optional Vertesia SDK version or package track for this scaffold. Overrides the deployment default.")
    create_version: Optional[StrictBool] = Field(default=None, description="Start an initial app version build after the source has been pushed. Defaults to true.")
    __properties: ClassVar[List[str]] = ["app_id", "title", "description", "modules", "appgen_package_spec", "create_version"]

    @field_validator('appgen_package_spec')
    def appgen_package_spec_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:latest|dev|dev-[0-9]+\.[0-9]+|snapshot-[0-9a-f]{7}|[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)$", value):
            raise ValueError(r"must validate the regular expression /^(?:latest|dev|dev-[0-9]+\.[0-9]+|snapshot-[0-9a-f]{7}|[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StartAppScaffoldRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StartAppScaffoldRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "app_id": obj.get("app_id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "modules": obj.get("modules"),
            "appgen_package_spec": obj.get("appgen_package_spec"),
            "create_version": obj.get("create_version")
        })
        return _obj


