# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260807.073259Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from vertesia_client.openapi.models.agent_tool_approval_class import AgentToolApprovalClass
from vertesia_client.openapi.models.json_schema import JSONSchema
from vertesia_client.openapi.models.mcp_tool_annotations import MCPToolAnnotations
from vertesia_client.openapi.models.process_tool_compatibility import ProcessToolCompatibility
from vertesia_client.openapi.models.tool_source import ToolSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ToolInspection(BaseModel):
    """
    ToolInspection
    """ # noqa: E501
    name: StrictStr
    source: ToolSource
    description: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    input_schema: Optional[JSONSchema] = Field(default=None, description="Exact input schema when the provider supplied one. Omitted rather than fabricated.")
    output_schema: Optional[JSONSchema] = Field(default=None, description="MCP outputSchema advertised by the provider. It does not describe the process node result transport.")
    output_contract_status: Optional[StrictStr] = Field(default=None, description="For app tools, whether the provider advertised output schema metadata. Omitted for builtin and interaction tools.")
    approval_class: Optional[AgentToolApprovalClass] = None
    annotations: Optional[MCPToolAnnotations] = None
    app_install_id: Optional[StrictStr] = None
    app_name: Optional[StrictStr] = None
    ready: StrictBool = Field(description="True only when an exact input schema was resolved.")
    process_compatibility: Optional[ProcessToolCompatibility] = None
    __properties: ClassVar[List[str]] = ["name", "source", "description", "title", "input_schema", "output_schema", "output_contract_status", "approval_class", "annotations", "app_install_id", "app_name", "ready", "process_compatibility"]

    @field_validator('output_contract_status')
    def output_contract_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolInspection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_schema
        if self.input_schema:
            _dict['input_schema'] = self.input_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_schema
        if self.output_schema:
            _dict['output_schema'] = self.output_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of annotations
        if self.annotations:
            _dict['annotations'] = self.annotations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of process_compatibility
        if self.process_compatibility:
            _dict['process_compatibility'] = self.process_compatibility.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolInspection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "source": obj.get("source"),
            "description": obj.get("description"),
            "title": obj.get("title"),
            "input_schema": JSONSchema.from_dict(obj["input_schema"]) if obj.get("input_schema") is not None else None,
            "output_schema": JSONSchema.from_dict(obj["output_schema"]) if obj.get("output_schema") is not None else None,
            "output_contract_status": obj.get("output_contract_status"),
            "approval_class": obj.get("approval_class"),
            "annotations": MCPToolAnnotations.from_dict(obj["annotations"]) if obj.get("annotations") is not None else None,
            "app_install_id": obj.get("app_install_id"),
            "app_name": obj.get("app_name"),
            "ready": obj.get("ready"),
            "process_compatibility": ProcessToolCompatibility.from_dict(obj["process_compatibility"]) if obj.get("process_compatibility") is not None else None
        })
        return _obj


