# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional, Union
from vertesia_client.openapi.models.webhook_payload_mode import WebhookPayloadMode
from vertesia_client.openapi.models.webhook_signing_mode import WebhookSigningMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WebhookEventDeliveryTarget(BaseModel):
    """
    WebhookEventDeliveryTarget
    """ # noqa: E501
    type: StrictStr
    url: StrictStr
    has_secret: StrictBool = Field(description="Server-managed: whether a signing secret is stored. Set by the server, never by callers.")
    secret_label: Optional[StrictStr] = Field(default=None, description="Server-managed: label of the active signing secret.")
    signing_mode: Optional[WebhookSigningMode] = None
    payload_mode: Optional[WebhookPayloadMode] = None
    headers: Optional[Dict[str, StrictStr]] = None
    encrypted_headers: Optional[StrictBool] = None
    timeout_ms: Optional[Union[StrictFloat, StrictInt]] = None
    result_path: Optional[StrictStr] = None
    custom_data: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["type", "url", "has_secret", "secret_label", "signing_mode", "payload_mode", "headers", "encrypted_headers", "timeout_ms", "result_path", "custom_data"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookEventDeliveryTarget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookEventDeliveryTarget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "url": obj.get("url"),
            "has_secret": obj.get("has_secret"),
            "secret_label": obj.get("secret_label"),
            "signing_mode": obj.get("signing_mode"),
            "payload_mode": obj.get("payload_mode"),
            "headers": obj.get("headers"),
            "encrypted_headers": obj.get("encrypted_headers"),
            "timeout_ms": obj.get("timeout_ms"),
            "result_path": obj.get("result_path"),
            "custom_data": obj.get("custom_data")
        })
        return _obj


