# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from vertesia_client.openapi.models.event_error import EventError
from vertesia_client.openapi.models.signal_event_properties import SignalEventProperties
from vertesia_client.openapi.models.workflow_run_event_activity import WorkflowRunEventActivity
from vertesia_client.openapi.models.workflow_run_event_child_workflow import WorkflowRunEventChildWorkflow
from vertesia_client.openapi.models.workflow_run_event_timer import WorkflowRunEventTimer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowRunEvent(BaseModel):
    """
    WorkflowRunEvent
    """ # noqa: E501
    event_id: Union[StrictFloat, StrictInt]
    event_time: Optional[StrictStr]
    event_type: StrictStr
    task_id: Optional[StrictStr] = None
    attempt: Union[StrictFloat, StrictInt]
    activity: Optional[WorkflowRunEventActivity] = None
    child_workflow: Optional[WorkflowRunEventChildWorkflow] = Field(default=None, alias="childWorkflow")
    signal: Optional[SignalEventProperties] = None
    timer: Optional[WorkflowRunEventTimer] = None
    error: Optional[EventError] = None
    result: Optional[Any] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["event_id", "event_time", "event_type", "task_id", "attempt", "activity", "childWorkflow", "signal", "timer", "error", "result"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowRunEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of activity
        if self.activity:
            _dict['activity'] = self.activity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of child_workflow
        if self.child_workflow:
            _dict['childWorkflow'] = self.child_workflow.to_dict()
        # override the default output from pydantic by calling `to_dict()` of signal
        if self.signal:
            _dict['signal'] = self.signal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of timer
        if self.timer:
            _dict['timer'] = self.timer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if event_time (nullable) is None
        # and model_fields_set contains the field
        if self.event_time is None and "event_time" in self.model_fields_set:
            _dict['event_time'] = None

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowRunEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "event_time": obj.get("event_time"),
            "event_type": obj.get("event_type"),
            "task_id": obj.get("task_id"),
            "attempt": obj.get("attempt"),
            "activity": WorkflowRunEventActivity.from_dict(obj["activity"]) if obj.get("activity") is not None else None,
            "childWorkflow": WorkflowRunEventChildWorkflow.from_dict(obj["childWorkflow"]) if obj.get("childWorkflow") is not None else None,
            "signal": SignalEventProperties.from_dict(obj["signal"]) if obj.get("signal") is not None else None,
            "timer": WorkflowRunEventTimer.from_dict(obj["timer"]) if obj.get("timer") is not None else None,
            "error": EventError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "result": obj.get("result")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


