# coding: utf-8

"""
    Vertesia API

    The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from vertesia_client.openapi.models.activity_task import ActivityTask
from vertesia_client.openapi.models.child_workflow_task import ChildWorkflowTask
from vertesia_client.openapi.models.signal_task import SignalTask
from vertesia_client.openapi.models.timer_task import TimerTask
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WORKFLOWTASK_ONE_OF_SCHEMAS = ["ActivityTask", "ChildWorkflowTask", "SignalTask", "TimerTask"]

class WorkflowTask(BaseModel):
    """
    WorkflowTask
    """
    # data type: ActivityTask
    oneof_schema_1_validator: Optional[ActivityTask] = None
    # data type: ChildWorkflowTask
    oneof_schema_2_validator: Optional[ChildWorkflowTask] = None
    # data type: SignalTask
    oneof_schema_3_validator: Optional[SignalTask] = None
    # data type: TimerTask
    oneof_schema_4_validator: Optional[TimerTask] = None
    actual_instance: Optional[Union[ActivityTask, ChildWorkflowTask, SignalTask, TimerTask]] = None
    one_of_schemas: Set[str] = { "ActivityTask", "ChildWorkflowTask", "SignalTask", "TimerTask" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WorkflowTask.model_construct()
        error_messages = []
        match = 0
        # validate data type: ActivityTask
        if not isinstance(v, ActivityTask):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ActivityTask`")
        else:
            match += 1
        # validate data type: ChildWorkflowTask
        if not isinstance(v, ChildWorkflowTask):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChildWorkflowTask`")
        else:
            match += 1
        # validate data type: SignalTask
        if not isinstance(v, SignalTask):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SignalTask`")
        else:
            match += 1
        # validate data type: TimerTask
        if not isinstance(v, TimerTask):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TimerTask`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WorkflowTask with oneOf schemas: ActivityTask, ChildWorkflowTask, SignalTask, TimerTask. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WorkflowTask with oneOf schemas: ActivityTask, ChildWorkflowTask, SignalTask, TimerTask. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ActivityTask
        try:
            instance.actual_instance = ActivityTask.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ChildWorkflowTask
        try:
            instance.actual_instance = ChildWorkflowTask.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SignalTask
        try:
            instance.actual_instance = SignalTask.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TimerTask
        try:
            instance.actual_instance = TimerTask.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WorkflowTask with oneOf schemas: ActivityTask, ChildWorkflowTask, SignalTask, TimerTask. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WorkflowTask with oneOf schemas: ActivityTask, ChildWorkflowTask, SignalTask, TimerTask. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ActivityTask, ChildWorkflowTask, SignalTask, TimerTask]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


